### ISSUE TITLE
python dependices in setup.py 

### ISSUE THREAD

**Issue by SteveQUT** [qcr/code_templates#11]
A more expanded setup.py with req embedded in setup.py could be useful

Example

https://github.com/qcr/armer/blob/master/setup.py

**Comment by btalb** [comment]
That example copies the structure from the [Robotics Toolbox for Python](https://github.com/petercorke/robotics-toolbox-python/blob/master/setup.py), which is a Python Package.

The structure in https://github.com/qcr/armer/blob/master/setup.py doesn't make much sense in a ROS package as ROS ignores most of these arguments to the `setup()` function (see [here](https://answers.ros.org/question/229250/catkin_make-not-installing-python-dependencies/)).

Armer [doesn't seem like it would work without ROS](https://github.com/qcr/armer/blob/3965bb6763bda3eb455e9e2c69a0b3c269c8e7bb/armer/armer.py#L12), so most will just get ignored.

For our `ros_package` template though I'll just keep it simple (no dual ROS / Python hybrid support).
