### ISSUE TITLE
Skipping all selections produces error in `ros_package` 

### ISSUE THREAD

**Issue by btalb** [qcr/code_templates#16]
```
ben@ben-meshify:~/tmp/template$ qcr_templates ros_package

--------------------------------------------------------------------------------
--------------------------- Getting latest templates ---------------------------
--------------------------------------------------------------------------------
Cloning into '/tmp/qcr_templates'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 41 (delta 0), reused 26 (delta 0), pack-reused 0
Unpacking objects: 100% (41/41), 13.79 KiB | 882.00 KiB/s, done.
Done

--------------------------------------------------------------------------------
--------------------------- Prompting user settings ----------------------------
--------------------------------------------------------------------------------
Package name (template): 
Package version (0.1.0): 
Author's name (Ben Talbot): 
Author's email (qcrbot@qut.edu.au): 
License type (BSD): 
Add a custom C++ ROS node with name (leave blank to skip): 
Add a custom Python ROS node with name (leave blank to skip): 
Add custom ROS message definition with name (leave blank to skip): 
Add custom ROS service definition with name (leave blank to skip): 
Add custom ROS action definition with name (leave blank to skip): 

--------------------------------------------------------------------------------
------------------------ Creating project from template ------------------------
--------------------------------------------------------------------------------
sending incremental file list
./
.files.yaml
.variables.yaml
CMakeLists.txt
README.md
package.xml
setup.py
action/
action/ADD_ACTIONS.action
include/
include/PACKAGE_NAME/
include/PACKAGE_NAME/ADD_CPP_NODE.h
msg/
msg/ADD_MSGS.msg
scripts/
scripts/ADD_PY_NODE
src/
src/ADD_CPP_NODE.cpp
src/PACKAGE_NAME/
src/PACKAGE_NAME/ADD_CPP_NODE.cpp
src/PACKAGE_NAME/ADD_PY_NODE.py
src/PACKAGE_NAME/__init__.py
srv/
srv/ADD_SERVICES.srv

sent 10,369 bytes  received 344 bytes  21,426.00 bytes/sec
total size is 8,988  speedup is 0.84
removed '.variables.yaml'
removed '.files.yaml'

--------------------------------------------------------------------------------
---------------------- Applying user settings to template ----------------------
--------------------------------------------------------------------------------
Remove unnecessary files based on file requirements map:
removed './action/ADD_ACTIONS.action'
removed directory './action/'
removed './include/PACKAGE_NAME/ADD_CPP_NODE.h'
removed directory './include/PACKAGE_NAME'
removed directory './include/'
removed './msg/ADD_MSGS.msg'
removed directory './msg/'
removed './scripts/ADD_PY_NODE'
removed directory './scripts/'
removed './src/ADD_CPP_NODE.cpp'
removed './src/PACKAGE_NAME/ADD_PY_NODE.py'
removed './src/PACKAGE_NAME/ADD_CPP_NODE.cpp'
removed './src/PACKAGE_NAME/__init__.py'
removed directory './src/PACKAGE_NAME'
removed directory './src/'
removed './srv/ADD_SERVICES.srv'
removed directory './srv/'
	Done

Renaming directories and files:
	Done

Resolving in-file template chunks:
sed: can't read 113,122d: No such file or directory
```

**Comment by SteveQUT** [comment]
I think this may be a bug in the package same occurred even with python node. 

`qcr template ros_package

--------------------------------------------------------------------------------
--------------------------- Getting latest templates ---------------------------
--------------------------------------------------------------------------------
Cloning into '/tmp/qcr_templates'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 41 (delta 0), reused 26 (delta 0), pack-reused 0
Unpacking objects: 100% (41/41), 13.79 KiB | 2.30 MiB/s, done.
Done

--------------------------------------------------------------------------------
--------------------------- Prompting user settings ----------------------------
--------------------------------------------------------------------------------
Package name (interface): 
Package version (0.1.0): 
Author's name (Steven Martin): 
Author's email (steven.martin@qut.edu.au): 
License type (BSD): 
Add a custom C++ ROS node with name (leave blank to skip): 
Add a custom Python ROS node with name (leave blank to skip): set_row_params
Add custom ROS message definition with name (leave blank to skip): 
Add custom ROS service definition with name (leave blank to skip): 
Add custom ROS action definition with name (leave blank to skip): 

--------------------------------------------------------------------------------
------------------------ Creating project from template ------------------------
--------------------------------------------------------------------------------
sending incremental file list
./
.files.yaml
.variables.yaml
CMakeLists.txt
README.md
package.xml
setup.py
action/
action/ADD_ACTIONS.action
include/
include/PACKAGE_NAME/
include/PACKAGE_NAME/ADD_CPP_NODE.h
msg/
msg/ADD_MSGS.msg
scripts/
scripts/ADD_PY_NODE
src/
src/ADD_CPP_NODE.cpp
src/PACKAGE_NAME/
src/PACKAGE_NAME/ADD_CPP_NODE.cpp
src/PACKAGE_NAME/ADD_PY_NODE.py
src/PACKAGE_NAME/__init__.py
srv/
srv/ADD_SERVICES.srv

sent 10,363 bytes  received 344 bytes  21,414.00 bytes/sec
total size is 8,988  speedup is 0.84
removed '.variables.yaml'
removed '.files.yaml'

--------------------------------------------------------------------------------
---------------------- Applying user settings to template ----------------------
--------------------------------------------------------------------------------
Remove unnecessary files based on file requirements map:
removed './action/ADD_ACTIONS.action'
removed directory './action/'
removed './include/PACKAGE_NAME/ADD_CPP_NODE.h'
removed directory './include/PACKAGE_NAME'
removed directory './include/'
removed './msg/ADD_MSGS.msg'
removed directory './msg/'
removed './src/ADD_CPP_NODE.cpp'
removed './src/PACKAGE_NAME/ADD_CPP_NODE.cpp'
removed './srv/ADD_SERVICES.srv'
removed directory './srv/'
	Done

Renaming directories and files:
renamed './src/PACKAGE_NAME' -> './src/interface'
renamed './scripts/ADD_PY_NODE' -> './scripts/set_row_params'
renamed './src/interface/ADD_PY_NODE.py' -> './src/interface/set_row_params.py'
	Done

Resolving in-file template chunks:
sed: can't read 113,122d: No such file or directory
`

**Comment by btalb** [comment]
Interesting pick-up; thanks for finding that. 

I'll look into a fix that addresses both concerns.

**Comment by btalb** [comment]
Nevermind, didn't see #17. Will address there.
